### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by shuhuiluo** [malik672/uniswap-sdk-core-rust#26]
Ideally, errors should be recoverable. However, currently `assert!` and `panic!` are used instead.

**Comment by malik672** [comment]
yep, how about custom errors or probably rust return type would be more viable

**Comment by shuhuiluo** [comment]
> yep, how about custom errors or probably rust return type would be more viable

An error enum derived from `thiserror` should do. It's just lots of refactoring.

**Comment by malik672** [comment]
would start soon

**Comment by malik672** [comment]
> > yep, how about custom errors or probably rust return type would be more viable
> 
> An error enum derived from `thiserror` should do. It's just lots of refactoring.

i've been doing a lot of refactoring, this would affect a lot implementation in v3

**Comment by shuhuiluo** [comment]
That's fine. Please release 0.8.0.

**Comment by malik672** [comment]
Will make a pr today, will do that after the pr
