### ISSUE TITLE
Ensure equivalence with upstream

### ISSUE THREAD

**Issue by shuhuiluo** [malik672/uniswap-sdk-core-rust#49]
The `addresses` mod differs from the official TS SDK after recent upstream updates. For example the [`swap_router02_address`](https://github.com/malik672/uniswap-sdk-core-rust/blob/master/src/addresses.rs#L487) function should be changed after https://github.com/Uniswap/sdk-core/pull/120. Same for `V2_FACTORY_ADDRESSES` after https://github.com/Uniswap/sdk-core/pull/115. Also `V2_ROUTER_ADDRESSES` was modified in https://github.com/Uniswap/sdk-core/pull/113.

**Comment by shuhuiluo** [comment]
Also should use lazy statics for address maps instead of functions to keep naming the same.

**Comment by shuhuiluo** [comment]
And add tests as in https://github.com/Uniswap/sdk-core/pull/120.

**Comment by malik672** [comment]
> Also should use lazy statics for address maps instead of functions to keep naming the same.

or just make make it constants

**Comment by malik672** [comment]
> And add tests as in [Uniswap/sdk-core#120](https://github.com/Uniswap/sdk-core/pull/120).

this is so funny, currently implementing it and it's failing all tests
