### ISSUE TITLE
Use a faster `HashMap` crate

### ISSUE THREAD

**Issue by shuhuiluo** [malik672/uniswap-sdk-core-rust#62]
I don't think hash collision is a concern for this crate. Consider using a faster `HashMap` impl than `std::collections::HashMap`.

Reference:
https://nnethercote.github.io/perf-book/hashing.html
https://nnethercote.github.io/perf-book/linting.html#disallowing-types

**Comment by malik672** [comment]
on it, btw should we make this crate wasm compartible

**Comment by shuhuiluo** [comment]
> on it, btw should we make this crate wasm compartible

We can. Should be compatible after getting rid of `std`?

**Comment by malik672** [comment]
> > on it, btw should we make this crate wasm compartible
> 
> We can. Should be compatible after getting rid of `std`?

yeah, this will take a lot of refactoring

**Comment by malik672** [comment]
FxHashMap
